services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BD\EzPlatformQueryFieldType\GraphQL\QueryFieldResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "QueryFieldValue", method: "resolveQueryField" }

    BD\EzPlatformQueryFieldType\GraphQL\QueryFieldDefinitionMapper:
        decorates: EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\FieldDefinitionMapper
        arguments:
            $innerMapper: '@BD\EzPlatformQueryFieldType\GraphQL\QueryFieldDefinitionMapper.inner'
