system:
    default:
        fielddefinition_settings_templates:
            -
                template: "BDPlatformQueryFieldTypeBundle::fielddefinition_settings.html.twig"
        fielddefinition_edit_templates:
            -
                template: "BDPlatformQueryFieldTypeBundle::field_types.html.twig"
        field_templates:
            -
                template: "BDPlatformQueryFieldTypeBundle::content_fields.html.twig"
